parted/table.c: Fix a warning when compiling with translation support
,----[ Output when compiling with translation support ]
|...
| table.c: In function 'table_add_row_from_strlist':
| table.c:168: warning: implicit declaration of function 'wcsdup'
| table.c:168: warning: assignment makes pointer from integer without a cast
`----

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 79fb9008cb516e8a227455d725b2f24a3aa1d37e)